manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: kaspinning # 感度調整参照変更
      url-base: https://github.com/kaspinning # 感度調整参照変更
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: kaspinning
      revision: main
  self:
    path: config
